[project]
name = "ag-102-monorepo"
version = "0.1.0"
description = "A Python monorepo example"
requires-python = ">=3.8"
dependencies = []

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
